directories:
  output: release
  buildResources: public
appId: com.youssef.dynamics
productName: Dynamics
files:
  - filter:
      - electron/**/*
      - node_modules/**/*
extraResources:
  - from: build
    to: build
  - from: music-server
    to: music-server
  - from: music-server/node_modules
    to: music-server/node_modules
asarUnpack:
  - '**/music-server/**/*'
extraMetadata:
  main: electron/main.js
linux:
  icon: build/logo.png
  target:
    - AppImage
win:
  icon: build/logo.ico
  target: nsis
electronVersion: 37.2.0
